### ISSUE TITLE
不知道为什么，明显感觉，这几天效率比前几天低了很多

### ISSUE THREAD

**Issue by xiaoliuzi** [xiaoliuzi/cpp-primer-practise#16]
@starwing

**Comment by starwing** [comment]
没压力了呗，我快被墨墨给折磨死了……

你这样不行的，感觉就不是自己愿意学，过两天兴趣退了就不行了。你想想看你到底为什么要坚持吧～

**Comment by xiaoliuzi** [comment]
我想把以前她所有的资料都拉黑，所有的联系方式都删除，一起都删掉，然后安下心，学技术，可以吗？



我想有提升，我能通过心理暗示来努力克制自己，约束自己来学技术，我想有技术提升。


太虐心了。


墨墨怎么了？她一直都挺乖的啊

**Comment by xiaoliuzi** [comment]
我想能不能先实际写点什么，这样我有个主线，有个目的，写出来还有成就感，慢慢也许会好一些。

**Comment by xiaoliuzi** [comment]
我会努力的，请放心。

**Comment by xiaoliuzi** [comment]
全部空间相关内容，已删。开始新的生活。
