### ISSUE TITLE
迭代器越界，编译不过

### ISSUE THREAD

**Issue by xiaoliuzi** [xiaoliuzi/cpp-primer-practise#5]
```C++
//二分查找
#include <iostream>
#include <string>
#include <vector>

using namespace std;


int main()
{
	vector<string> text{ "abc","cdb", "cff", "efg","hello", "hij" };
	auto begin = text.begin();
	auto end = text.end();
	auto mid = text.begin() + (begin - end) / 2;

	string keyword;
	cin >> keyword;

	while (text.begin() != text.end()&& (keyword != *mid) ) {
		if (keyword < *mid) {
			end = mid - 1;
			//end = mid; //C ++ Primer version
		}
		else
			begin = mid + 1;
		mid = text.begin() + (begin - end) / 2;
	}

	if (keyword == *mid)
		cout << "found the string " << keyword << endl;

	if (text.begin() == text.end()) {
		cout << "Can not found" << endl;
	}

	return 0;
} 

```

编译没有问题，运行报错

Expression: vector iterator + offset out of range

debug以后，在这一行出现越界问题

auto mid = text.begin() + (begin - end) / 2;

**Comment by xiaoliuzi** [comment]
另，书中说的是如果待查找的字是小于mid迭代器所指向的内容，那么，执行

```C++
end = mid;
```

但我觉得，如果是数组

```C++
end = mid - 1;
```
比较有效率，书中这样写是因为，迭代器end实际上是最后一个元素的下一个地址，所以，迭代器end应该是end=mid; 等价于数组中的end = mid -1;

**Comment by starwing** [comment]
算mis错了，你begin-end是个负数吧？

end指的是最后一个元素的**后面一个**的位置，你没仔细看书吧？

**Comment by starwing** [comment]
以后任务遇到了问题，直接在issue下面问并@，不要新建新的issue，除非你找到了一个已经关闭的issue提到的任务的bug，这个时候新建issue，用#引用任务issue。

还有，你就一点都不想整理一下项目的目录结构吗？

**Comment by xiaoliuzi** [comment]
哦、的确是的， begin-end是个负数。

那这里的end =mid;就相当于数组实现二分查找中的mid-1对吗。

**Comment by starwing** [comment]
是的

**Comment by xiaoliuzi** [comment]
我想整理项目结构了，但没有找到如何创建目录

**Comment by starwing** [comment]
还有那个词叫exception，不是expression，给我认真点！

**Comment by xiaoliuzi** [comment]
是Expression，是的，冤枉啊

**Comment by starwing** [comment]
是的吗？你用的啥编译器？VS？

**Comment by xiaoliuzi** [comment]
嗯、是的，VS2015 Community.

**Comment by xiaoliuzi** [comment]
Solved the issue.

**Comment by starwing** [comment]
这样啊……我试了下，是expression，他的意思是加法这个表达式造成了溢出。是我的错。

**Comment by xiaoliuzi** [comment]
哦，还是溢出比较合理，我一直以为是越界。当时也不知道怎么搭错筋了，然后用begin减去end。

**Comment by xiaoliuzi** [comment]
其实我的确不够认真，昨晚状态有点遭，然后今天书放枕头下了，白天借同事盗版书，看了一天。
